# Generated by Django 5.2.17 on 2026-09-20 07:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default=django.utils.timezone.now, help_text='About me. Markdown is fine; React will render it later.'),
            preserve_default=False,
        ),
    ]
