# Generated by Django 5.2.17 on 2026-09-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, help_text='About me. Markdown is fine; React will render it later.'),
        ),
    ]
